apiVersion: v1
kind: Service
metadata:
  labels:
    run: nqv
  name: nqv
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
  selector:
    run: nqv
  type: LoadBalancer
