steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['get', 'github.com/spf13/hugo']
  env: ['PROJECT_ROOT=.']
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['get', 'github.com/mjibson/esc']
  env: ['PROJECT_ROOT=.']
- name: 'alpine'
  args: ['../gopath/bin/hugo']
  dir: 'blog'
- name: 'alpine'
  args: ['../gopath/bin/esc', '-o', 'static.go', '-prefix=public', '-pkg=blog', 'public']
  dir: 'blog'
- name: 'gcr.io/cloud-builders/go:alpine'
  args: ['install', 'github.com/not-quite-vacation/blog/preview']
  env: ['PROJECT_ROOT=github.com/not-quite-vacation/blog']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blog:$BRANCH_NAME', '.']

images: ['gcr.io/$PROJECT_ID/blog:$BRANCH_NAME']
