languageCode = "en-us"
title = "Not Quite Vacation"
baseURL = "https://www.notquitevacation.com/"
theme = "nqv-theme"
disqusShortname = "notquitevacation"
googleAnalytics = "UA-115470687-1"

[taxonomies]
category = "categories"
country = "countries"
tag = "tags"
series = "series"