languageCode = "en-us"
title = "Not Quite Vacation"
baseURL = "https://www.notquitevacation.com/"
theme = "nqv-theme"
disqusShortname = "notquitevacation"
googleAnalytics = "G-VNHXLJ7QBN"

[taxonomies]
category = "categories"
country = "countries"
tag = "tags"
series = "series"

[params]
placesVisited = [ 
    "United Kingdom",
    "Ireland",
    "France",
    "Belgium",
    "Netherlands",
    "Germany",
    "Czech Republic",
    "Austria",
    "Vietnam",
    "Cambodia",
    "Laos",
    "Thailand",
    "Taiwan",
    "Japan",
    "New Zealand",
    "Portugal",
    "Spain",
    "Italy",
]
navTaxonomies = ["categories", "countries"]
